config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'

  devise_for :admins, controllers: {
    sessions: "admin/devise/sessions",
    passwords: "admin/devise/passwords",
    registrations: "admin/devise/registrations"
  }

  devise_for :users, controllers: {
    sessions: "users_devise/sessions",
    passwords: "users_devise/passwords",
    registrations: "users_devise/registrations"
  }
  #admin
  namespace :admin do
    resources :muscles
    resources :genres, except: [:show]
  end

  #user
  get 'homes/top'
  resources :users, only: [:show]
  resources :muscles, only: [:index,:show] do
    get 'search', on: :collection
  end
  resources :genres, only: [:index]
  resources :notes do
    resource :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    get 'search', on: :collection
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :note
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :muscles, foreign_key: :genre_id, dependent: :destroy
  attachment :image

  validates :name, presence: true
  validates :image, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :note
end

app/models/muscle.rb
class Muscle < ApplicationRecord
  belongs_to :genre
  has_many :muscle_images, dependent: :destroy

  accepts_attachments_for :muscle_images, attachment: :images
  accepts_nested_attributes_for :muscle_images, allow_destroy: true

  validates :name, presence: true
  validates :origin, presence: true
  validates :insertion, presence: true
  validates :innervation, presence: true
  validates :action, presence: true
  validates :information, length: { maximum: 500 }
  validates :genre_id, presence: true

  def self.search(search)
    return Muscle.all unless search
    Muscle.where(['name LIKE ?', "%#{search}%"])
  end
end

app/models/muscle_image.rb
class MuscleImage < ApplicationRecord
  belongs_to :muscle

  attachment :image
  validates :image, presence: true
end

app/models/note.rb
class Note < ApplicationRecord
  has_many :note_images, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { maximum: 20 }
  validates :name, presence: true
  validates :body, presence: true

  scope :with_user, -> { includes(:user) }
  scope :with_likes, -> { includes(:likes) }

  def self.search(search)
    return Note.all unless search
    Note.where(['name LIKE ?', "%#{search}%"])
  end

  def liked_by?(user)
    likes.exists?(user_id: user.id)
  end

end

app/models/note_image.rb
class NoteImage < ApplicationRecord
  belongs_to :note

  attachment :image
  accepts_attachments_for :note_images, attachment: :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :notes, dependent: :destroy
  has_many :likes
  has_many :comments, dependent: :destroy

end

app/controllers/admin/muscles_controller.rb
class Admin::MusclesController < Admin::BaseController
  before_action :authenticate_admin!
  before_action :set_muscle, only: [:show, :edit, :update, :destroy]

  def new
    @muscle = Muscle.new
    2.times { @muscle.muscle_images.build }
  end

  def create
    @muscle = Muscle.new(muscle_params)
    if @muscle.save
      redirect_to admin_muscle_path(@muscle.id), notice:'新しい筋肉を作成しました'
    else
      render action: :new
    end
  end

  def index
    @muscles = Muscle.where(genre_id: params[:genre_id]).page(params[:page]).per(10)
  end

  def show; end

  def edit; end

  def update
    if @muscle.update(muscle_params)
      redirect_to admin_muscle_path(@muscle.id), notice:'筋肉を編集しました'
    else
      render action: :edit
    end
  end

  def destroy
    @muscle.destroy
    redirect_to admin_genres_path, alert:'筋肉を削除しました'
  end

  private

  def set_muscle
    @muscle = Muscle.find(params[:id])
  end

  def muscle_params
    params.require(:muscle).permit(:genre_id, :name, :innervation, :action, :origin, :insertion, :information, muscle_images_attributes:[:image, :_destroy, :id])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top; end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_note, only: [:create, :destroy]

  def create
    like = current_user.likes.build(note_id: params[:note_id])
    like.save!
  end

  def destroy
    like = Like.find_by(note_id: params[:note_id], user_id: current_user.id)
    like.destroy!
  end

  private

  def set_note
    @note = Note.find(params[:note_id])
  end
end

app/controllers/muscles_controller.rb
class MusclesController < ApplicationController

  def index
    @muscles = Muscle.where(genre_id: params[:genre_id])
    @genres = Genre.all
  end

  def show
    @muscle = Muscle.find(params[:id])
    @note = Note.new
  end

  def search
    @muscles = Muscle.search(params[:search])
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]

  def new
    @note = Note.new
  end

  def create
    @note = current_user.notes.build(note_params)
    if @note.save
      redirect_to user_path(current_user.id), notice: 'ノートを作成しました'
    else
      render 'new'
    end
  end

  def index
    @notes = Note
               .all
               .with_user
               .with_likes
               .page(params[:page]).per(10).reverse_order
  end

  def show
    @user = User.find(@note.user_id)
    @comment = Comment.new
  end

  def edit; end

  def update
    if @note.update(note_params)
      redirect_to user_path(current_user.id), notice: 'ノートを編集しました'
    else
      render 'edit'
    end
  end

  def destroy
    @note.destroy!
    redirect_to user_path(current_user.id), notice: 'ノートを削除しました'
  end

  def search
    @notes = Note.search(params[:search]).reverse_order
  end

private

  def set_note
    @note = Note.find(params[:id])
  end

  def correct_user
    @user = @note.user
    unless @user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def note_params
    params.require(:note).permit(:user_id, :name, :title, :body)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user

  def show
    @note = Note.new
    @notes = @user.notes.page(params[:page]).per(10).order('created_at DESC')
    @user = User.find_by(id: params[:id])
    @likes = Like.where(user_id: @user.id)
  end

  private

  def correct_user
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/admin/muscles_helper.rb
module Admin::MusclesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def muscle_action_label(num)
    num.zero? ? "※動作前" : "※動作後"
  end

  def select_muscle_image_label(num)
    "#{muscle_action_label(num)}の筋肉を選択してください"
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/muscles_helper.rb
module MusclesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/muscles/edit.html.erb
<div class="container">
  <div class="row row-contents-margin-bottom">
    <%= link_to :back do %>
      <i class="fas fa-backward">戻る</i>
    <% end %>
    <h1>筋肉編集</h1>
    <div class="col-xs-4">
      <%= form_for [:admin, @muscle] do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        <% index = 0 %>
        <%= f.fields_for "muscle_images" do |muscle_image_form| %>
          <p><%= muscle_image_form.label :muscle_images, select_muscle_image_label(index) %><span class="input-required">※必須</span></p>
          <%= muscle_image_form.attachment_field :image, class: "previewble" %>
          <div class="preview">
            <%= attachment_image_tag @muscle.muscle_images[index], :image, :size => '250x400' %>
          </div>
          <% index += 1 %>
        <% end %>
    </div>

    <div class="col-xs-8">
      <div class="form-group">
        <%= f.label :name, '筋肉名' %><span class="input-required">※必須</span>
        <p><%= f.text_field :name %></p>
      </div>
      <div class="form-group">
        <%= f.label :origin, '起始' %><span class="input-required">※必須</span>
        <p><%= f.text_field :origin %></p>
      </div>
      <div class="form-group">
        <%= f.label :insertion, '停止' %><span class="input-required">※必須</span>
        <p><%= f.text_field :insertion %></p>
      </div>
      <div class="form-group">
        <%= f.label :innervation, '支配神経' %><span class="input-required">※必須</span>
        <p><%= f.text_field :innervation, class: "form-control" %></p>
      </div>
      <div class="form-group">
        <%= f.label :action, '作用' %><span class="input-required">※必須</span>
        <p><%= f.text_field :action, class: "form-control" %></p>
      </div>
      <div class="form-group">
        <%= f.label :genre_id, '部位' %><span class="input-required">※必須</span>
        <p><%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "--選択してください--" %></p>
      </div>
      <div class="form-group">
        <%= f.label :information, '追加情報' %>
        <p><%= f.text_area :information, class: 'form-control input-lg' %></p>
      </div>
      <div class="text-right">
        <%= f.submit '変更する', class: "btn btn-success" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/admin/muscles/index.html.erb
<div class="container">
  <%= link_to :back do %>
    <i class="fas fa-backward">戻る</i>
  <% end %>
  <h1>筋肉一覧</h1>
  <div class="new-muscle-btn text-right">
    <%= link_to "筋肉を追加する", new_admin_muscle_path, class: "btn btn-success" %>
  </div>
  <table class="table muscle-index-table">
    <thead>
      <tr>
        <th>筋肉名</th>
        <th>起始</th>
        <th>停止</th>
        <th>支配神経</th>
        <th>作用</th>
        <th>部位</th>
      </tr>
    </thead>
    <tbody>
      <% @muscles.each do |muscle| %>
      <tr>
        <td><%= link_to muscle.name, admin_muscle_path(muscle.id) %></td>
        <td><%= muscle.origin %></td>
        <td><%= muscle.insertion %></td>
        <td><%= muscle.innervation %></td>
        <td><%= muscle.action %></td>
        <td><%= muscle.genre.name %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <div class="paginate-area text-center">
    <%= paginate @muscles %>
  </div>

</div>

app/views/admin/muscles/new.html.erb
<div class="container">
  <div class="row row-contents-margin-bottom">
    <h1>筋肉登録画面</h1>
    <div class="col-xs-4">
      <%= form_for [:admin, @muscle] do |f| %>
        <% index = 0 %>
        <%= render 'layouts/error_messages', model: f.object %>
        <%= f.fields_for "muscle_images" do |muscle_image_form| %>
        <p><%= muscle_image_form.label :muscle_images, select_muscle_image_label(index) %><span class="input-required">※必須</span></p>
        <%= muscle_image_form.attachment_field :image, class: "previewble" %>
        <div class="preview">
          <%= image_tag 'sample_image.jpg', :size => '250x250' %>
        </div>
        <% index += 1 %>
      <% end %>
    </div>

    <div class="col-xs-8">
      <div class="form-group">
        <%= f.label :name, '筋肉名' %><span class="input-required">※必須</span>
        <p><%= f.text_field :name %></p>
      </div>
      <div class="form-group">
        <%= f.label :origin, '起始' %><span class="input-required">※必須</span>
        <p><%= f.text_field :origin, class: "form-control" %></p>
      </div>
      <div class="form-group">
        <%= f.label :insertion, '停止' %><span class="input-required">※必須</span>
        <p><%= f.text_field :insertion, class: "form-control" %></p>
      </div>
      <div class="form-group">
        <%= f.label :innervation, '支配神経' %><span class="input-required">※必須</span>
        <p><%= f.text_field :innervation, class: "form-control" %></p>
      </div>
      <div class="form-group">
        <%= f.label :action, '作用' %><span class="input-required">※必須</span>
        <p><%= f.text_field :action, class: "form-control" %></p>
      </div>
      <div class="form-group">
        <%= f.label :genre_id, '部位' %><span class="input-required">※必須</span>
        <p><%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "--選択してください--" %></p>
      </div>
      <div class="form-group">
        <%= f.label :information, '追加情報' %>
        <p><%= f.text_area :information, class: 'form-control input-lg' %></p>
      </div>
      <div class="text-right">
        <%= f.submit '作成する', class: "btn btn-success" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/muscles/show.html.erb
<div class="container">
  <div class="row">
    <div class="notice-message">
      <%= flash[:notice] %>
    </div>
    <%= link_to :back do %>
      <i class="fas fa-backward">戻る</i>
    <% end %>
    <h1><%= @muscle.name %></h1>
    <div class="col-xs-4">
      <% @muscle.muscle_images.each.with_index do |image, index| %>
        <h3><%= muscle_action_label(index) %></h3>
        <p><%= attachment_image_tag image, :image, :fill, 250, 400 %></p>
      <% end %>
    </div>
    <div class="col-xs-8">
      <table class="table muscle-show-table">
        <tr>
          <th>支配神経</th>
          <td><%= @muscle.innervation %></td>
        </tr>
        <tr>
          <th>起始</th>
          <td><%= @muscle.origin %></td>
        </tr>
        <tr>
          <th>停止</th>
          <td><%= @muscle.insertion %></td>
        </tr>
        <tr>
          <th>作用</th>
          <td><%= @muscle.action %></td>
        </tr>
        <tr>
          <th>部位</th>
          <td><%= @muscle.genre.name %></td>
        </tr>
        <tr>
          <th>追加情報</th>
          <td><%= @muscle.information %></td>
        </tr>
      </table>
      <div class="text-right">
        <%= link_to "編集する", edit_admin_muscle_path, class: "btn btn-success" %>
        <%= link_to "削除する", admin_muscle_path(@muscle.id), method: :delete, data:{confirm: "この筋肉を削除しますか？"}, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/muscles/index.html.erb
<div class="container">
  <div class="row">
    <div>
      <%= link_to :back do %>
        <i class="fas fa-backward">戻る</i>
      <% end %>
    </div>
    <div class="search-form-content text-right">
      <%= form_tag(search_muscles_path, :method => 'get' ) do %>
        <%= text_field_tag :search, '', placeholder: "筋肉名を入力" %>
        <%= submit_tag '検索する', :name => nil, class: "btn btn-primary" %>
      <% end %>
    </div>
    <div class="heading-title text-center">
      <h1 class="heading-style">筋肉一覧</h1>
      <h3>Muscle List</h3>
    </div>
  </div>
  <table class="table muscle-index-table">
    <thead>
      <tr>
        <th>筋肉名</th>
        <th>起始</th>
        <th>停止</th>
        <th>支配神経</th>
        <th>作用</th>
        <th>部位</th>
      </tr>
    </thead>
    <tbody>
      <% @muscles.each do |muscle| %>
        <tr>
          <td><%= link_to muscle.name, muscle_path(muscle.id) %></td>
          <td><%= muscle.origin %></td>
          <td><%= muscle.insertion %></td>
          <td><%= muscle.innervation %></td>
          <td><%= muscle.action %></td>
          <td><%= muscle.genre.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/muscles/search.html.erb
<div class="container">
  <div class="row">
    <div>
      <%= link_to :back do %>
        <i class="fas fa-backward">戻る</i>
      <% end %>
    </div>
    <div class="search-form-content text-right">
      <%= form_tag(search_muscles_path, :method => 'get' ) do %>
        <%= text_field_tag :search, '', placeholder: "筋肉名を入力" %>
        <%= submit_tag '検索する', :name => nil, class: "btn btn-primary" %>
      <% end %>
    </div>
    <div class="heading-title text-center">
      <h1 class="heading-style">筋肉一覧</h1>
      <h3>Muscle List</h3>
    </div>
  </div>
  <% if @muscles.empty? %>
    <h3>条件に合う筋肉が見つかりませんでした</h3>
  <% end %>
    <table class="table muscle-index-table">
      <thead>
        <tr>
          <th>筋肉名</th>
          <th>起始</th>
          <th>停止</th>
          <th>支配神経</th>
          <th>作用</th>
          <th>部位</th>
        </tr>
      </thead>
      <tbody>
        <% @muscles.each do |muscle| %>
          <tr>
            <td><%= link_to muscle.name, muscle_path(muscle.id) %></td>
            <td><%= muscle.origin %></td>
            <td><%= muscle.insertion %></td>
            <td><%= muscle.innervation %></td>
            <td><%= muscle.action %></td>
            <td><%= muscle.genre.name %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/muscles/show.html.erb
<div class="container">
  <div class="row">
    <div>
      <%= link_to :back do %>
        <i class="fas fa-backward">戻る</i>
      <% end %>
    </div>
    <div class="text-center">
      <div class="heading-title">
        <h1 class="heading-style"><%= @muscle.name %></h1>
      </div>
      <% @muscle.muscle_images.each.with_index do |image,index| %>
        <div class="muscle-aciton-card">
          <h4><%= muscle_action_label(index) %></h4>
          <%= attachment_image_tag image, :image, :fill, 250, 400 %>
        </div>
      <% end %>
    </div>
    <div class="col-xs-offset-1 col-xs-10">
      <table class="table muscle-show-table">
        <tr>
          <th>起始</th>
          <td><%= @muscle.origin %></td>
        </tr>
        <tr>
          <th>停止</th>
          <td><%= @muscle.insertion %></td>
        </tr>
        <tr>
          <th>支配神経</th>
          <td><%= @muscle.innervation %></td>
        </tr>
        <tr>
          <th>作用</th>
          <td><%= @muscle.action %></td>
        </tr>
        <tr>
          <th>部位</th>
          <td><%= @muscle.genre.name %></td>
        </tr>
        <tr>
          <th>追加情報</th>
          <td><%= @muscle.information %></td>
        </tr>
      </table>
      <div class="heading-title text-center">
        <h2 class="heading-style">ノートを書く</h2>
        <h3>Writing Note</h3>
      </div>
      <%= render partial: 'notes/note_new', locals: {note: @note} %>
    </div>
  </div>
</div>