config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'

  devise_for :admins, controllers: {
    sessions: "admin/devise/sessions",
    passwords: "admin/devise/passwords",
    registrations: "admin/devise/registrations"
  }

  devise_for :users, controllers: {
    sessions: "users_devise/sessions",
    passwords: "users_devise/passwords",
    registrations: "users_devise/registrations"
  }
  #admin
  namespace :admin do
    resources :muscles
    resources :genres, except: [:show]
  end

  #user
  get 'homes/top'
  resources :users, only: [:show]
  resources :muscles, only: [:index,:show] do
    get 'search', on: :collection
  end
  resources :genres, only: [:index]
  resources :notes do
    resource :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    get 'search', on: :collection
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :note
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :muscles, foreign_key: :genre_id, dependent: :destroy
  attachment :image

  validates :name, presence: true
  validates :image, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :note
end

app/models/muscle.rb
class Muscle < ApplicationRecord
  belongs_to :genre
  has_many :muscle_images, dependent: :destroy

  accepts_attachments_for :muscle_images, attachment: :images
  accepts_nested_attributes_for :muscle_images, allow_destroy: true

  validates :name, presence: true
  validates :origin, presence: true
  validates :insertion, presence: true
  validates :innervation, presence: true
  validates :action, presence: true
  validates :information, length: { maximum: 500 }
  validates :genre_id, presence: true

  def self.search(search)
    return Muscle.all unless search
    Muscle.where(['name LIKE ?', "%#{search}%"])
  end
end

app/models/muscle_image.rb
class MuscleImage < ApplicationRecord
  belongs_to :muscle

  attachment :image
  validates :image, presence: true
end

app/models/note.rb
class Note < ApplicationRecord
  has_many :note_images, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { maximum: 20 }
  validates :name, presence: true
  validates :body, presence: true

  scope :with_user, -> { includes(:user) }
  scope :with_likes, -> { includes(:likes) }

  def self.search(search)
    return Note.all unless search
    Note.where(['name LIKE ?', "%#{search}%"])
  end

  def liked_by?(user)
    likes.exists?(user_id: user.id)
  end

end

app/models/note_image.rb
class NoteImage < ApplicationRecord
  belongs_to :note

  attachment :image
  accepts_attachments_for :note_images, attachment: :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :notes, dependent: :destroy
  has_many :likes
  has_many :comments, dependent: :destroy

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

  def index
    @genres = Genre.all
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top; end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_note, only: [:create, :destroy]

  def create
    like = current_user.likes.build(note_id: params[:note_id])
    like.save!
  end

  def destroy
    like = Like.find_by(note_id: params[:note_id], user_id: current_user.id)
    like.destroy!
  end

  private

  def set_note
    @note = Note.find(params[:note_id])
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]

  def new
    @note = Note.new
  end

  def create
    @note = current_user.notes.build(note_params)
    if @note.save
      redirect_to user_path(current_user.id), notice: 'ノートを作成しました'
    else
      render 'new'
    end
  end

  def index
    @notes = Note
               .all
               .with_user
               .with_likes
               .page(params[:page]).per(10).reverse_order
  end

  def show
    @user = User.find(@note.user_id)
    @comment = Comment.new
  end

  def edit; end

  def update
    if @note.update(note_params)
      redirect_to user_path(current_user.id), notice: 'ノートを編集しました'
    else
      render 'edit'
    end
  end

  def destroy
    @note.destroy!
    redirect_to user_path(current_user.id), notice: 'ノートを削除しました'
  end

  def search
    @notes = Note.search(params[:search]).reverse_order
  end

private

  def set_note
    @note = Note.find(params[:id])
  end

  def correct_user
    @user = @note.user
    unless @user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def note_params
    params.require(:note).permit(:user_id, :name, :title, :body)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user

  def show
    @note = Note.new
    @notes = @user.notes.page(params[:page]).per(10).order('created_at DESC')
    @user = User.find_by(id: params[:id])
    @likes = Like.where(user_id: @user.id)
  end

  private

  def correct_user
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def muscle_action_label(num)
    num.zero? ? "※動作前" : "※動作後"
  end

  def select_muscle_image_label(num)
    "#{muscle_action_label(num)}の筋肉を選択してください"
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/muscles_helper.rb
module MusclesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/likes/_like.html.erb
<% if user_signed_in? %>
  <% if note.liked_by?(current_user) %>
    <%= link_to note_likes_path(note.id), method: :delete, remote: true do %>
      <i class="fa fa-heart" style="color: red;"></i>
      <%= note.likes.count %>
    <% end %>
  <% else %>
    <%= link_to note_likes_path(note.id), method: :post, remote: true do %>
      <i class="fa fa-heart" style="color: gray;"></i>
      <%= note.likes.count %>
    <% end %>
  <% end %>
<% else %>
  <i class="fa fa-heart" aria-hidden="true" style="color: gray;"></i><%= note.likes.count %>
<% end %>

app/views/likes/create.js.erb
$('#likes_buttons_<%= @note.id %>').html("<%= j(render partial: 'likes/like', locals: {note: @note}) %>");

app/views/likes/destroy.js.erb
$('#likes_buttons_<%= @note.id %>').html("<%= j(render partial: 'likes/like', locals: {note: @note}) %>");

app/views/notes/_note_new.html.erb
<div class="col-xs-offset-1 col-xs-10">
  <%= form_for(@note) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <div class="form-group form-width">
      <%= f.label :tile, 'タイトル' %><span class="input-required">※必須</span>
      <%= f.text_field :title, class: "form-control note-title-form" %>
    </div>
    <div class="form-group form-width">
      <%= f.label :name, '筋肉名' %><span class="input-required">※必須</span>
      <%= f.text_field :name, class: "form-control note-title-form" %>
    </div>
    <div class="form-group">
      <%= f.label :body, '内容' %><span class="input-required">※必須</span><span>
      （語呂合わせや動作についてまとめましょう）</span>
      <%= f.text_area :body, 'data-provider': :summernote %>
    </div>
    <div class="btn-area text-right">
      <%= f.submit class: "btn btn-success" %>
    </div>
  <% end %>
</div>

app/views/notes/edit.html.erb
<div class="container">
  <div class="row">
    <div>
      <%= link_to :back do %>
        <i class="fas fa-backward">戻る</i>
      <% end %>
    </div>
    <div class="heading-title text-center">
      <h2 class="heading-style">ノートを編集する</h2>
      <h3>Edit Note</h3>
    </div>
    <%= render partial: 'note_new', locals: {note: @note} %>
  </div>
</div>

app/views/notes/index.html.erb
<div class="container">
  <div class="row">
    <div class="text-right">
      <%= form_tag(search_notes_path, :method => 'get' ) do %>
        <%= text_field_tag :search, '', placeholder: "筋肉名を入力" %>
        <%= submit_tag '検索する', :name => nil, class: "btn btn-primary" %>
        <div class="writing-note-btn">
          <%= link_to "ノートを書く", new_note_path, class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
    <div class="heading-title text-center">
      <h2 class="heading-style">ノート一覧</h2>
      <h3>Note List</h3>
    </div>
  </div>
  <table class="table notes_index_table">
    <thead>
      <tr>
        <th>ノート名</th>
        <th>筋肉名</th>
        <th>作成者</th>
        <th>作成日時</th>
      </tr>
    </thead>
    <tbody>
      <% @notes.each do |note| %>
        <tr>
          <td><%= link_to note.title, note_path(note.id) %></td>
          <td><%= note.name %></td>
          <td><%= note.user.name %></td>
          <td><%= l note.created_at, format: :short %></td>
          <td id="likes_buttons_<%= note.id %>"><%= render partial: 'likes/like', locals: {note: note} %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="paginate-area text-center">
    <%= paginate @notes %>
  </div>
</div>

app/views/notes/new.html.erb
<div class="heading-title text-center">
  <h2 class="heading-style">ノートを書く</h2>
  <h3>Writing Note</h3>
</div>
<%= render partial: 'note_new', locals: {note: @note} %>

app/views/notes/search.html.erb
<div class="container">
  <div class="row">
    <div>
      <%= link_to :back do %>
        <i class="fas fa-backward">戻る</i>
      <% end %>
    </div>
    <div class="text-right">
      <%= form_tag(search_notes_path, :method => 'get' ) do %>
        <%= text_field_tag :search, '', placeholder: "筋肉名を入力" %>
        <%= submit_tag '検索する', :name => nil, class: "btn btn-primary" %>
      <% end %>
    </div>
    <div class="heading-title text-center">
      <h2 class="heading-style">ノート一覧</h2>
      <h3>Note List</h3>
    </div>
  </div>
  <% if @notes.empty? %>
    <h3>条件に合うノートが見つかりませんでした</h3>
  <% end %>
  <table class="table">
    <thead>
      <tr>
        <th>ノート名</th>
        <th>筋肉名</th>
        <th>作成者</th>
        <th>作成日時</th>
      </tr>
    </thead>
    <tbody>
      <% @notes.each do |note| %>
        <tr>
          <td><%= link_to note.title, note_path(note.id) %></td>
          <td><%= note.name %></td>
          <td><%= note.user.name %></td>
          <td><%= l note.created_at, format: :short %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/notes/show.html.erb
<div class="container">
 <div>
  <%= link_to :back do %>
  <i class="fas fa-backward">戻る</i>
  <% end %>
</div>
<div class="row row-contents-margin-bottom">
  <div class="col-xs-offset-1 col-xs-10">
    <h2 class="heading-style">
      <%= @note.title %>
    </h2>
    <%= l @note.created_at, format: :short %>
    <span id="likes_buttons_<%= @note.id %>">
     <%= render partial: 'likes/like', locals: {note: @note} %>
   </span>
   <% if current_user.id == @user.id %>
   <div class="text-right">
     <%= link_to "編集する", edit_note_path(@note.id), class: "btn btn-success" %>
     <%= link_to "削除する", note_path(@note.id), method: :delete, data:{ confirm: "このノートを削除しますか？"}, class: "btn btn-danger" %>
   </div>
   <% end %>
   <tr>
     <td>
       <h3>ノート内容</h3>
     </td>
     <td><%= @note.body.html_safe %></td>
   </tr>
   <h2><%= @note.comments.count %>件コメント</h2>
   <% @note.comments.each do |comment| %>
     <%= comment.user.name %>
     <%= comment.created_at.strftime('%Y/%m/%d') %>
     <%= comment.comment %>
     <% if comment.user == current_user %>
       <%= link_to "削除", note_comment_path(comment.note, comment), method: :delete %>
     <% end %>
   <% end %>
   <%= form_for [@note, @comment] do |f| %>
     <p><%= f.text_area :comment, rows:'5', placeholder: "コメントをここに" %></p>
     <%= f.submit "送信する" %>
   <% end %>

 </div>
</div>
</div>

app/views/users/show.html.erb
<ul class="tab clearfix">
  <li class="active">マイノート</li>
  <li>ブックマーク</li>
  <li>ノートを書く</li>
</ul>
<div class="area container">
  <ul class="show">
    <li text>
      <p id ="notice"><%= flash[:notice] %></p>
      <div class="heading-title text-center">
        <h2 class="heading-style">マイノート一覧</h2>
        <h3>My Note</h3>
      </div>
      <table class="table">
        <thead>
          <tr>
            <th>ノート名</th>
            <th>筋肉名</th>
            <th>作成日時</th>
          </tr>
        </thead>
        <tbody>
          <% @notes.each do |note| %>
            <tr>
              <td><%= link_to note.title, note_path(note.id) %></td>
              <td><%= note.name %></td>
              <td><%= l note.created_at, format: :short %></td>
              <td id="likes_buttons_<%= note.id %>"><%= render partial: 'likes/like', locals: {note: note} %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= paginate @notes %>
    </li>
  </ul>
  <ul>
    <li>
      <div class="heading-title text-center">
        <h2 class="heading-style">ブックマーク一覧</h2>
        <h3>Book Mark</h3>
      </div>
      <table class="table">
        <thead>
          <tr>
            <th>ノート名</th>
            <th>筋肉名</th>
          </tr>
        </thead>
        <tbody>
          <% @likes.each do |like| %>
            <tr>
              <% note = Note.find_by(id: like.note_id) %>
              <td><%= link_to note.title, note_path(note.id) %></td>
              <td><%= note.name %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </li>
  </ul>
  <ul>
    <li>
      <div class="heading-title text-center">
        <h2 class="heading-style">ノートを書く</h2>
        <h3>Writing Note</h3>
      </div>
      <%= render partial: 'notes/note_new', locals: {note: @note} %>
    </li>
  </ul>
</div>