config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'

  devise_for :admins, controllers: {
    sessions: "admin/devise/sessions",
    passwords: "admin/devise/passwords",
    registrations: "admin/devise/registrations"
  }

  devise_for :users, controllers: {
    sessions: "users_devise/sessions",
    passwords: "users_devise/passwords",
    registrations: "users_devise/registrations"
  }
  #admin
  namespace :admin do
    resources :muscles
    resources :genres, except: [:show]
  end

  #user
  get 'homes/top'
  resources :users, only: [:show]
  resources :muscles, only: [:index,:show] do
    get 'search', on: :collection
  end
  resources :genres, only: [:index]
  resources :notes do
    resource :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    get 'search', on: :collection
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :note
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :muscles, foreign_key: :genre_id, dependent: :destroy
  attachment :image

  validates :name, presence: true
  validates :image, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :note
end

app/models/muscle.rb
class Muscle < ApplicationRecord
  belongs_to :genre
  has_many :muscle_images, dependent: :destroy

  accepts_attachments_for :muscle_images, attachment: :images
  accepts_nested_attributes_for :muscle_images, allow_destroy: true

  validates :name, presence: true
  validates :origin, presence: true
  validates :insertion, presence: true
  validates :innervation, presence: true
  validates :action, presence: true
  validates :information, length: { maximum: 500 }
  validates :genre_id, presence: true

  def self.search(search)
    return Muscle.all unless search
    Muscle.where(['name LIKE ?', "%#{search}%"])
  end
end

app/models/muscle_image.rb
class MuscleImage < ApplicationRecord
  belongs_to :muscle

  attachment :image
  validates :image, presence: true
end

app/models/note.rb
class Note < ApplicationRecord
  has_many :note_images, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { maximum: 20 }
  validates :name, presence: true
  validates :body, presence: true

  scope :with_user, -> { includes(:user) }
  scope :with_likes, -> { includes(:likes) }

  def self.search(search)
    return Note.all unless search
    Note.where(['name LIKE ?', "%#{search}%"])
  end

  def liked_by?(user)
    likes.exists?(user_id: user.id)
  end

end

app/models/note_image.rb
class NoteImage < ApplicationRecord
  belongs_to :note

  attachment :image
  accepts_attachments_for :note_images, attachment: :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :notes, dependent: :destroy
  has_many :likes
  has_many :comments, dependent: :destroy

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < Admin::BaseController
  before_action :authenticate_admin!
  before_action :set_genre, only: [:edit, :update, :destroy]

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "新しい部位を追加しました。"
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render action: :index
    end
  end

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
    @genres = Genre.all
  end

  def update
    if @genre.update(genre_params)
      flash[:notice] = "部位を編集しました。"
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render action: :edit
    end
  end

  def destroy
    @genre.destroy
    flash[:alert] = "部位を削除しました。"
    redirect_to admin_genres_path
  end

  private

  def set_genre
    @genre = Genre.find(params[:id])
  end

  def genre_params
    params.require(:genre).permit(:name, :image)
  end

end

app/controllers/genres_controller.rb
class GenresController < ApplicationController

  def index
    @genres = Genre.all
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top; end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_note, only: [:create, :destroy]

  def create
    like = current_user.likes.build(note_id: params[:note_id])
    like.save!
  end

  def destroy
    like = Like.find_by(note_id: params[:note_id], user_id: current_user.id)
    like.destroy!
  end

  private

  def set_note
    @note = Note.find(params[:note_id])
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]

  def new
    @note = Note.new
  end

  def create
    @note = current_user.notes.build(note_params)
    if @note.save
      redirect_to user_path(current_user.id), notice: 'ノートを作成しました'
    else
      render 'new'
    end
  end

  def index
    @notes = Note
               .all
               .with_user
               .with_likes
               .page(params[:page]).per(10).reverse_order
  end

  def show
    @user = User.find(@note.user_id)
    @comment = Comment.new
  end

  def edit; end

  def update
    if @note.update(note_params)
      redirect_to user_path(current_user.id), notice: 'ノートを編集しました'
    else
      render 'edit'
    end
  end

  def destroy
    @note.destroy!
    redirect_to user_path(current_user.id), notice: 'ノートを削除しました'
  end

  def search
    @notes = Note.search(params[:search]).reverse_order
  end

private

  def set_note
    @note = Note.find(params[:id])
  end

  def correct_user
    @user = @note.user
    unless @user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

  def note_params
    params.require(:note).permit(:user_id, :name, :title, :body)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user

  def show
    @note = Note.new
    @notes = @user.notes.page(params[:page]).per(10).order('created_at DESC')
    @user = User.find_by(id: params[:id])
    @likes = Like.where(user_id: @user.id)
  end

  private

  def correct_user
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def muscle_action_label(num)
    num.zero? ? "※動作前" : "※動作後"
  end

  def select_muscle_image_label(num)
    "#{muscle_action_label(num)}の筋肉を選択してください"
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/muscles_helper.rb
module MusclesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="row row-contents-margin-bottom">
    <div class="col-xs-3">
      <%= link_to "<<戻る", :back %>
      <h1>部位編集</h1>
      <%= form_for [:admin, @genre] do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        <%= f.label :image, "画像" %><span class="input-required">※必須</span>
        <%= f.attachment_field :image, class: "previewble" %>
        <div class="preview">
          <%= attachment_image_tag @genre, :image, :size => '250x400' %>
        </div>
        <p><%= f.label :name, "部位名" %><span class="input-required">※必須</span></p>
        <%= f.text_field :name %>
        <%= f.submit '変更する', class: "btn btn-success" %>
      <% end %>
    </div>

    <div class="col-xs-9 text-center">
      <div class="genre-heading">
        <h1>部位一覧</h1>
      </div>
      <div class="admin-genre-card-content">
        <% @genres.each do |genre| %>
          <div class="genre-card">
            <p class="genre-card-muscle-name"><%= "部位：#{genre.name}" %></p>
            <%= attachment_image_tag genre, :image, :size => '250x400' %>
            <div class="genre-card-edit">
              <%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-success" %>
              <%= link_to "削除する", admin_genre_path(genre.id), method: :delete, data:{confirm: "この部位を削除しますか？"}, class: "btn btn-danger" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
      <%= render 'layouts/error_messages', model: @genre %>
      <div class="notice-message">
        <%= flash[:notice] %>
      </div>
      <div class="alert-message">
        <%= flash[:alert] %>
      </div>
      <h1>部位追加</h1>
      <%= form_for [:admin, @genre] do |f| %>
        <%= f.label :image, "画像" %><span class="input-required">※必須</span>
        <%= f.attachment_field :image, class: "previewble" %>
        <div class="preview">
          <%= image_tag 'sample_image.jpg', :size => '250x400' %>
        </div>
        <p><%= f.label :name, "部位名" %><span class="input-required">※必須</span></p>
        <%= f.text_field :name %>
        <%= f.submit '作成する', class: "btn btn-success"  %>
      <% end %>
    </div>

    <div class="col-xs-9 text-center">
      <div class="genre-heading">
        <h1>部位一覧</h1>
      </div>
      <div class="admin-genre-card-content">
        <% @genres.each do |genre| %>
          <%= link_to admin_muscles_path(genre_id: genre.id) do %>
            <div class="genre-card">
              <p class="genre-card-muscle-name"><%= "部位：#{genre.name}" %></p>
              <%= attachment_image_tag genre, :image, :size => '250x400' %>
              <div class="genre-card-edit">
                <%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-success" %>
                <%= link_to "削除する", admin_genre_path(genre.id), method: :delete, data:{confirm: "この部位を削除しますか？"}, class: "btn btn-danger" %>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/genres/index.html.erb
<div class="container">
  <div class="row">
    <div class="search-form-content text-right">
      <%= form_tag(search_muscles_path, :method => 'get' ) do %>
        <%= text_field_tag :search, '', placeholder: "筋肉名を入力" %>
        <%= submit_tag '検索する', :name => nil, class: "btn btn-primary" %>
      <% end %>
    </div>
    <div class="text-center">
      <h2 class="heading-style">部位一覧</h2>
      <h3>Part Muscle</h3>
    </div>
  </div>
  <div class="row">
    <div id="sample" class="genre-card-content text-center fade_off">
      <% @genres.each do |genre| %>
        <%= link_to muscles_path(genre_id: genre.id) do %>
          <div class="genre-card">
            <div class="genre-card-title">
              <p class="genre-card-muscle-name"><%= "#{genre.name}" %></p>
            </div>
            <%= attachment_image_tag genre, :image, :size => '250x400' %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>