config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'

  devise_for :admins, controllers: {
    sessions: "admin/devise/sessions",
    passwords: "admin/devise/passwords",
    registrations: "admin/devise/registrations"
  }

  devise_for :users, controllers: {
    sessions: "users_devise/sessions",
    passwords: "users_devise/passwords",
    registrations: "users_devise/registrations"
  }
  #admin
  namespace :admin do
    resources :muscles
    resources :genres, except: [:show]
  end

  #user
  get 'homes/top'
  resources :users, only: [:show]
  resources :muscles, only: [:index,:show] do
    get 'search', on: :collection
  end
  resources :genres, only: [:index]
  resources :notes do
    resource :likes, only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
    get 'search', on: :collection
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :note
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :muscles, foreign_key: :genre_id, dependent: :destroy
  attachment :image

  validates :name, presence: true
  validates :image, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :note
end

app/models/muscle.rb
class Muscle < ApplicationRecord
  belongs_to :genre
  has_many :muscle_images, dependent: :destroy

  accepts_attachments_for :muscle_images, attachment: :images
  accepts_nested_attributes_for :muscle_images, allow_destroy: true

  validates :name, presence: true
  validates :origin, presence: true
  validates :insertion, presence: true
  validates :innervation, presence: true
  validates :action, presence: true
  validates :information, length: { maximum: 500 }
  validates :genre_id, presence: true

  def self.search(search)
    return Muscle.all unless search
    Muscle.where(['name LIKE ?', "%#{search}%"])
  end
end

app/models/muscle_image.rb
class MuscleImage < ApplicationRecord
  belongs_to :muscle

  attachment :image
  validates :image, presence: true
end

app/models/note.rb
class Note < ApplicationRecord
  has_many :note_images, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { maximum: 20 }
  validates :name, presence: true
  validates :body, presence: true

  scope :with_user, -> { includes(:user) }
  scope :with_likes, -> { includes(:likes) }

  def self.search(search)
    return Note.all unless search
    Note.where(['name LIKE ?', "%#{search}%"])
  end

  def liked_by?(user)
    likes.exists?(user_id: user.id)
  end

end

app/models/note_image.rb
class NoteImage < ApplicationRecord
  belongs_to :note

  attachment :image
  accepts_attachments_for :note_images, attachment: :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :notes, dependent: :destroy
  has_many :likes
  has_many :comments, dependent: :destroy

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top; end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_note, only: [:create, :destroy]

  def create
    like = current_user.likes.build(note_id: params[:note_id])
    like.save!
  end

  def destroy
    like = Like.find_by(note_id: params[:note_id], user_id: current_user.id)
    like.destroy!
  end

  private

  def set_note
    @note = Note.find(params[:note_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def muscle_action_label(num)
    num.zero? ? "※動作前" : "※動作後"
  end

  def select_muscle_image_label(num)
    "#{muscle_action_label(num)}の筋肉を選択してください"
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/muscles_helper.rb
module MusclesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>study-muscle</title>
  <link href="https://fonts.googleapis.com/earlyaccess/kokoro.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Kalam&display=swap" rel="stylesheet">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <header>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to image_tag('muscle-icon.png', :size => '100x100'), admin_genres_path %>
        </div>
        <div class="collapse navbar-collapse" id="navbarEexample5">
          <ul class="nav navbar-nav navbar-right">
            <% if admin_signed_in? %>
              <li><%= link_to "部位一覧", admin_genres_path %></li>
              <li><%= link_to "筋肉の作成", new_admin_muscle_path %></li>
              <li><%= link_to "ログアウト", destroy_admin_session_path, method: :delete %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header><!-- /header -->
  <%= yield %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StudyMuscle</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>

<body>
  <header>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to image_tag('muscle-icon.png', :size => '100x100'), root_path %>
          <% if user_signed_in? %>
          <span class="rogin-user-name">
            <%= "#{current_user.name}さんがログイン中" %>
          </span>
          <% else %>
          <span class="not-rogin">ログインしていません</span>
          <% end %>
        </div>
        <div class="collapse navbar-collapse navbar-right" id="navbarEexample1">
          <ul class="nav navbar-nav">
            <li><%= link_to "TOP", homes_top_path %></li>
            <li><%= link_to "部位から探す", genres_path %></li>
            <% if user_signed_in? %>
            <li><%= link_to "MyNote", user_path(current_user.id) %></li>
            <li><%= link_to "Note一覧", notes_path %></li>
            <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
            <% else %>
            <li><%= link_to "新規登録", new_user_registration_path %></li>
            <li><%= link_to "ログイン", new_user_session_path %></li>
            <li><%= link_to "管理人はこちら", new_admin_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
  </header><!-- /header -->
  <%= yield %>
</body>
</html>